[phases.setup]
aptPkgs = [
    "...",
    "libgl1",
    "libglib2.0-0",
    "libsm6",
    "libxrender1",
    "libxext6",
    "libxcb1",
    "libxcb-render0",
    "libxcb-shape0",
    "libxcb-xfixes0"
]
